-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Rates exposing (eur, gbp, jpy, usd)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


eur : SelectionSet (Maybe Float) Api.Object.Rates
eur =
    Object.selectionForField "(Maybe Float)" "eur" [] (Decode.float |> Decode.nullable)


gbp : SelectionSet (Maybe Float) Api.Object.Rates
gbp =
    Object.selectionForField "(Maybe Float)" "gbp" [] (Decode.float |> Decode.nullable)


jpy : SelectionSet (Maybe Float) Api.Object.Rates
jpy =
    Object.selectionForField "(Maybe Float)" "jpy" [] (Decode.float |> Decode.nullable)


usd : SelectionSet (Maybe Float) Api.Object.Rates
usd =
    Object.selectionForField "(Maybe Float)" "usd" [] (Decode.float |> Decode.nullable)
