-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (PercentNotional(..), Rates(..), Summary(..))


type PercentNotional
    = PercentNotional


type Rates
    = Rates


type Summary
    = Summary
